{{- with .Values.serviceAccount }}
{{- if .create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backend-app.serviceAccountName" $ }}
  labels:
    {{- include "backend-app.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
